# Generated by Django 4.2.6 on 2023-10-21 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 21, 18, 11, 368063)
            ),
        ),
    ]
