# Generated by Django 4.2.6 on 2023-10-22 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0010_alter_todoitem_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 29, 13, 25, 29, 222119)
            ),
        ),
    ]
