# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: todo
type: Opaque
data:
  # DATABASE_PASSWORD: <base64-encoded-password> # Use base64 to encode your real password
  # SECRET_KEY: <base64-encoded-django-secret-key>

